#use_frameworks!
source 'https://github.com/rocedar/RocedarPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RCHealthEvaluationComponet_Example' do
  pod 'RCHealthEvaluationComponet', :path => '../'

  target 'RCHealthEvaluationComponet_Tests' do
    inherit! :search_paths

    
  end
end
